# Generated by Django 6.0.4 on 2026-05-07 02:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('building', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_threshold', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('task_name', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('Tuning', 'Tuning'), ('Regulation', 'Regulation'), ('Voicing', 'Voicing'), ('Cleaning', 'Cleaning'), ('Inspection', 'Inspection'), ('Other', 'Other')], max_length=20)),
                ('interval_days', models.IntegerField()),
                ('warning_days_before', models.IntegerField(default=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_performed', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='PartUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('cost_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts_used', to='maintenance.maintenancelog')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='maintenance.part')),
            ],
            options={
                'verbose_name': 'Part Used',
                'verbose_name_plural': 'Parts Used',
            },
        ),
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('piano_type', models.CharField(choices=[('Grand', 'Grand'), ('Upright', 'Upright'), ('Digital', 'Digital')], max_length=20)),
                ('year_built', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2100)])),
                ('year_acquired', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2100)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pianos', to='maintenance.location')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='maintenance.piano'),
        ),
        migrations.CreateModel(
            name='ConditionReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_before_cents', models.DecimalField(blank=True, db_column='pitch_before_cents', decimal_places=2, max_digits=6, null=True)),
                ('pitch_after_cents', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_f', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_rating', models.CharField(blank=True, choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_readings', to='maintenance.maintenancelog')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_readings', to='maintenance.piano')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('Tuning', 'Tuning'), ('Regulation', 'Regulation'), ('Voicing', 'Voicing'), ('Cleaning', 'Cleaning'), ('Inspection', 'Inspection'), ('Other', 'Other')], max_length=20)),
                ('interval_days', models.IntegerField()),
                ('warning_days_before', models.IntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='maintenance.piano')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='maintenance.scheduletemplate')),
            ],
            options={
                'ordering': ['piano', 'task_type'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='technician',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='maintenance.team'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Request', 'Request'), ('Emergency', 'Emergency')], max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.piano')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenanceschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_profile_photo', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('piano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.piano')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by_name', models.CharField(blank=True, max_length=200)),
                ('reported_by_email', models.EmailField(blank=True, max_length=254)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved')], default='New', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='maintenance.piano')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='maintenance.workorder'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('piano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.piano')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Overdue', 'Overdue'), ('Due Soon', 'Due Soon')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
