# Generated by Django 5.2 on 2026-04-16 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('task_name', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('Tuning', 'Tuning'), ('Regulation', 'Regulation'), ('Voicing', 'Voicing'), ('Cleaning', 'Cleaning'), ('Inspection', 'Inspection'), ('Other', 'Other')], max_length=20)),
                ('interval_days', models.IntegerField()),
                ('warning_days_before', models.IntegerField(default=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='technician',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='maintenance.scheduletemplate'),
        ),
    ]
