# Generated by Django 6.0.4 on 2026-05-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piano',
            old_name='brand',
            new_name='make',
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='belly_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='case_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='hammers_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='keys_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='pedals_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='pinblock_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='regulation_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='soundboard_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='strings_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='voicing_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='belly_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='case_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='cleaning_interval_unit',
            field=models.CharField(choices=[('months', 'Months'), ('days', 'Days')], default='months', max_length=10),
        ),
        migrations.AddField(
            model_name='piano',
            name='cleaning_interval_value',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='piano',
            name='current_humidity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='current_pitch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='current_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='hammers_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='keys_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='location_in_venue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='piano',
            name='next_cleaning_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='next_regulation_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='next_tuning_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='next_voicing_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='pedals_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='pinblock_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='regulation_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='regulation_interval_unit',
            field=models.CharField(choices=[('months', 'Months'), ('days', 'Days')], default='months', max_length=10),
        ),
        migrations.AddField(
            model_name='piano',
            name='regulation_interval_value',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='piano',
            name='soundboard_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='strings_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='tuning_interval_unit',
            field=models.CharField(choices=[('months', 'Months'), ('days', 'Days')], default='months', max_length=10),
        ),
        migrations.AddField(
            model_name='piano',
            name='tuning_interval_value',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='piano',
            name='voicing_condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
        migrations.AddField(
            model_name='piano',
            name='voicing_interval_unit',
            field=models.CharField(choices=[('months', 'Months'), ('days', 'Days')], default='months', max_length=10),
        ),
        migrations.AddField(
            model_name='piano',
            name='voicing_interval_value',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='conditionreading',
            name='overall_rating',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Needs Immediate Attention', 'Needs Immediate Attention')], max_length=30),
        ),
    ]
