# Generated by Django 6.0.4 on 2026-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_piano_schema_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='task_type',
            field=models.CharField(blank=True, choices=[('Tuning', 'Tuning'), ('Regulation', 'Regulation'), ('Voicing', 'Voicing'), ('Cleaning', 'Cleaning'), ('Inspection', 'Inspection'), ('Other', 'Other')], help_text='Matches against piano maintenance schedule (Tuning, Regulation, etc.)', max_length=20),
        ),
    ]
