# Generated by Django 6.0.4 on 2026-04-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_add_last_service_date_and_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
