# Generated by Django 5.2 on 2026-04-17 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piano',
            name='date_acquired',
        ),
        migrations.AddField(
            model_name='piano',
            name='year_acquired',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='piano',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
