# Generated by Django 6.0.4 on 2026-04-18 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_piano_year_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionreading',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
