# Generated by Django 6.0.4 on 2026-04-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_add_piano_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionreading',
            old_name='pitch_offset_cents',
            new_name='pitch_before_cents',
        ),
    ]
