# Generated by Django 6.0.4 on 2026-05-08 18:56

import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_piano_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='service_visit',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', validators=[maintenance.models.validate_image_file]),
        ),
        migrations.DeleteModel(
            name='ServiceVisit',
        ),
    ]
