# Generated by Django 6.0.4 on 2026-05-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_remove_servicevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='maintenance.workorder'),
        ),
    ]
