# Generated by Django 6.0.4 on 2026-05-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_workorder_log_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionreading',
            name='piano_display',
            field=models.CharField(blank=True, help_text='Preserved piano name after piano deletion.', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='piano_display',
            field=models.CharField(blank=True, help_text='Preserved piano name after piano deletion.', max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='piano_display',
            field=models.CharField(blank=True, help_text='Preserved piano name after piano deletion.', max_length=200),
        ),
        migrations.AddField(
            model_name='piano',
            name='venue_display',
            field=models.CharField(blank=True, help_text='Preserved venue name after venue deletion.', max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='piano_display',
            field=models.CharField(blank=True, help_text='Preserved piano name after piano deletion.', max_length=200),
        ),
        migrations.AlterField(
            model_name='conditionreading',
            name='piano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_readings', to='maintenance.piano'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='piano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='maintenance.piano'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='piano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='maintenance.piano'),
        ),
        migrations.AlterField(
            model_name='partused',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='maintenance.maintenancelog'),
        ),
        migrations.AlterField(
            model_name='piano',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pianos', to='maintenance.venue'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='piano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.piano'),
        ),
    ]
