# Generated by Django 6.0.4 on 2026-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_team_technician_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionreading',
            name='pitch_before_cents',
            field=models.DecimalField(blank=True, db_column='pitch_before_cents', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
