# Generated by Django 6.0.4 on 2026-05-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_soft_delete_display_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='maintenance.organization'),
        ),
    ]
