# Generated by Django 6.0.4 on 2026-04-18 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_alter_conditionreading_pitch_before_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='skip_next',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overdue', 'Overdue'), ('due_soon', 'Due Soon')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('work_order', 'alert_type')},
            },
        ),
    ]
