# Generated by Django 6.0.4 on 2026-05-08 23:45

from django.db import migrations


def drop_tables_if_exist(apps, schema_editor):
    """Drop tables that may or may not exist in the database."""
    cursor = schema_editor.connection.cursor()
    for table in ['maintenance_attachment', 'maintenance_alert', 'maintenance_team']:
        try:
            cursor.execute(f'DROP TABLE IF EXISTS "{table}"')
        except Exception:
            pass


def remove_team_column(apps, schema_editor):
    """Remove the team_id column from technician if it exists."""
    cursor = schema_editor.connection.cursor()
    # Check if column exists
    cursor.execute("PRAGMA table_info(maintenance_technician)")
    columns = [row[1] for row in cursor.fetchall()]
    if 'team_id' in columns:
        # SQLite doesn't support DROP COLUMN before 3.35, use Django's approach
        try:
            cursor.execute(
                'ALTER TABLE "maintenance_technician" DROP COLUMN "team_id"'
            )
        except Exception:
            pass  # Old SQLite; column will just be ignored


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_org_venue_set_null'),
    ]

    operations = [
        migrations.RunPython(remove_team_column, migrations.RunPython.noop),
        migrations.RunPython(drop_tables_if_exist, migrations.RunPython.noop),
    ]
