# Generated by Django 6.0.4 on 2026-05-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_remove_team_alert_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('default_labor_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default hourly labor rate for cost calculations.', max_digits=8)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        # State-only: tell Django the removed models are gone.
        # The actual tables were already dropped in migration 0010.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='attachment', name='piano'),
                migrations.RemoveField(model_name='attachment', name='work_order'),
                migrations.RemoveField(model_name='team', name='manager'),
                migrations.RemoveField(model_name='technician', name='team'),
                migrations.DeleteModel(name='Alert'),
                migrations.DeleteModel(name='Attachment'),
                migrations.DeleteModel(name='Team'),
            ],
            database_operations=[],
        ),
    ]
