# Generated by Django 6.0.4 on 2026-05-09 00:33

from django.db import migrations, models


def set_existing_users_both_roles(apps, schema_editor):
    """Existing users get both roles to preserve current behavior."""
    Technician = apps.get_model('maintenance', 'Technician')
    Technician.objects.all().update(role_admin=True, role_technician=True)


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='role_admin',
            field=models.BooleanField(default=False, help_text='Can manage all settings, create/edit/delete records, and assign work.'),
        ),
        migrations.AddField(
            model_name='technician',
            name='role_technician',
            field=models.BooleanField(default=True, help_text='Can be assigned work orders and log their own work.'),
        ),
        migrations.RunPython(set_existing_users_both_roles, migrations.RunPython.noop),
    ]
