# Generated by Django 5.2.14 on 2026-05-13 19:24

import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_lock_down_supabase_public_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%y/%m/%d/', validators=[maintenance.models.validate_image_file]),
        ),
    ]
