# Generated by Django 6.0.4 on 2026-05-14 04:04

import django.db.models.deletion
import maintenance.models
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_default_company(apps, schema_editor):
    Company = apps.get_model('maintenance', 'Company')
    Technician = apps.get_model('maintenance', 'Technician')
    CompanyMembership = apps.get_model('maintenance', 'CompanyMembership')
    Organization = apps.get_model('maintenance', 'Organization')
    Venue = apps.get_model('maintenance', 'Venue')
    Piano = apps.get_model('maintenance', 'Piano')
    ScheduleTemplate = apps.get_model('maintenance', 'ScheduleTemplate')
    MaintenanceSchedule = apps.get_model('maintenance', 'MaintenanceSchedule')
    WorkOrder = apps.get_model('maintenance', 'WorkOrder')
    MaintenanceLog = apps.get_model('maintenance', 'MaintenanceLog')
    ConditionReading = apps.get_model('maintenance', 'ConditionReading')
    Part = apps.get_model('maintenance', 'Part')
    PartUsed = apps.get_model('maintenance', 'PartUsed')
    MaintenanceRequest = apps.get_model('maintenance', 'MaintenanceRequest')
    Photo = apps.get_model('maintenance', 'Photo')
    CompanySettings = apps.get_model('maintenance', 'CompanySettings')
    Tag = apps.get_model('maintenance', 'Tag')

    base_name = 'Default Company'
    slug = slugify(base_name)
    company, _ = Company.objects.get_or_create(
        slug=slug,
        defaults={'name': base_name, 'is_active': True},
    )

    for model in [
        Organization,
        Venue,
        Piano,
        ScheduleTemplate,
        MaintenanceSchedule,
        WorkOrder,
        MaintenanceLog,
        ConditionReading,
        Part,
        PartUsed,
        MaintenanceRequest,
        Photo,
        Tag,
    ]:
        model.objects.filter(company__isnull=True).update(company=company)

    for user in Technician.objects.all():
        CompanyMembership.objects.get_or_create(
            company=company,
            user=user,
            defaults={
                'role_admin': getattr(user, 'role_admin', False),
                'role_technician': getattr(user, 'role_technician', True),
                'is_active': getattr(user, 'is_active', True),
            },
        )

    settings_rows = list(CompanySettings.objects.filter(company__isnull=True))
    if settings_rows:
        company_settings = settings_rows[0]
        company_settings.company = company
        company_settings.save(update_fields=['company'])
        for extra in settings_rows[1:]:
            extra.company = company
            extra.save(update_fields=['company'])
    else:
        CompanySettings.objects.create(company=company, company_name=company.name)


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_lock_down_supabase_public_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('role_admin', models.BooleanField(default=False)),
                ('role_technician', models.BooleanField(default=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_admin', models.BooleanField(default=False)),
                ('role_technician', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company__name', 'user__username'],
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%y/%m/%d/', validators=[maintenance.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('target_model', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='maintenance.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='conditionreading',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition_readings', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='part',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='partused',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='photo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='piano',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pianos', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='tag',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='venue',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='maintenance.company'),
        ),
        migrations.RunPython(backfill_default_company, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_tag_name_per_company'),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_company_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='maintenance.company'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='companyinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company', 'email', 'status'), name='unique_pending_invitation_per_company_email'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_company_membership'),
        ),
    ]
