# Generated by Django 6.0.4 on 2026-05-15 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_company_companyinvitation_companymembership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='conditionreading',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_readings', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='part',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='partused',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='piano',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pianos', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='maintenance.company'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='maintenance.company'),
        ),
    ]
