# Generated by Django 5.2.14 on 2026-07-13 13:30

import django.db.models.functions.text
from django.db import migrations, models


def normalize_identity_emails(apps, schema_editor):
    Technician = apps.get_model('maintenance', 'Technician')
    CompanyInvitation = apps.get_model('maintenance', 'CompanyInvitation')

    normalized_users = {}
    user_updates = []
    for user_id, email in Technician.objects.values_list('pk', 'email'):
        normalized = (email or '').strip().casefold()
        if normalized:
            existing_user_id = normalized_users.get(normalized)
            if existing_user_id is not None:
                raise RuntimeError(
                    'Cannot enforce case-insensitive user email uniqueness: '
                    f'users {existing_user_id} and {user_id} have the same email.'
                )
            normalized_users[normalized] = user_id
        if email != normalized:
            user_updates.append((user_id, normalized))

    pending_invitations = {}
    invitation_updates = []
    for invitation_id, company_id, status, email in CompanyInvitation.objects.values_list(
        'pk', 'company_id', 'status', 'email'
    ):
        normalized = (email or '').strip().casefold()
        if status == 'pending':
            key = (company_id, normalized)
            existing_invitation_id = pending_invitations.get(key)
            if existing_invitation_id is not None:
                raise RuntimeError(
                    'Cannot enforce case-insensitive pending invitation uniqueness: '
                    f'invitations {existing_invitation_id} and {invitation_id} conflict.'
                )
            pending_invitations[key] = invitation_id
        if email != normalized:
            invitation_updates.append((invitation_id, normalized))

    for user_id, email in user_updates:
        Technician.objects.filter(pk=user_id).update(email=email)
    for invitation_id, email in invitation_updates:
        CompanyInvitation.objects.filter(pk=invitation_id).update(email=email)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('maintenance', '0018_jobrun'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyinvitation',
            name='unique_pending_invitation_per_company_email',
        ),
        migrations.RunPython(normalize_identity_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='companyinvitation',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('email'), condition=models.Q(('status', 'pending')), name='unique_pending_invitation_company_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='technician',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='unique_technician_email_ci'),
        ),
    ]
