# Generated by Django 5.2.16 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_identity_email_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='photos/thumbnails/%y/%m/%d/'),
        ),
    ]
