# Generated by Django 5.2.16 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_photo_thumbnail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'target_model', 'target_id', '-created_at'], name='audit_target_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['company', '-created_at'], name='wo_company_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(condition=models.Q(('status__in', ['Open', 'In Progress'])), fields=['company', 'due_date', '-created_at'], name='wo_active_due_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['piano', 'task_type', 'status', '-completed_date'], name='wo_service_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['company', '-created_at'], name='request_company_recent_idx'),
        ),
    ]
